data outliney5;
set sasuser.xb;
if (y5 not in(1,2,3,4,5,.));
proc print;
run;
data outliney5;
set sasuser.xb;
where (y5 not in(1,2,3,4,5,.));
proc print;
run;
data outliney5;
set sasuser.xb;
if _n_=7;
proc print;
run;
data outliney5;
set sasuser.xb;
where _n_=7;
proc print;
run;
data age;
set sasuser.xb;
if age<30 then ageg=1;
else ageg=2;
if ageg=1;
proc print;
run;
data age;
set sasuser.xb;
if age<30 then ageg=1;
else ageg=2;
where ageg=1;
proc print;
run;
