ods rtf file="g:\myods\bmi1.rtf" style=fgs bodytitle startpage=never;       
proc tabulate data=bmi;
class gender bd;       
var fbg;              
table fbg*(n mean std) bd*(n colpctn),gender=""/ misstext="--";
label fbg="血糖" gender="性别" bd="体型";                
keylabel n="例数" mean="均数" std="标准差" colpctn="百分比(%)";     
title "表1 两组基线资料比较";
run;
ods rtf close;
